- hosts: group1
  tasks:
    - name: docker configuration
      yum_repository:
        name: docker-repository
        baseurl: https://download.docker.com/linux/centos/7/x86_64/stable/
        enabled: true
        gpgcheck: no
        description: docker repository
    - name: installing docker package
      command: "yum install docker-ce -y --nobest"
    - name: install docker-ce python packagde
      command: "pip3 install docker"
      ignore_errors: true
    - name: starting docker service
      service:
        name: "docker"
        state: started
        enabled: yes
    - name: install python3 
      package: 
        name: python36
        state: present
    - name: stop firewall
      service:
        name: "firewalld"
        state: stopped
    - name: pull httpd server image
      docker_image:
        name: "httpd"
        source: pull



